title: Your Blog Name
description: A brief description of your blog
author: Your Name
email: your-email@example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Site settings
baseurl: ""
url: "https://your-username.github.io"
