title: Dr Kembhavi's Blog
description: "I write everything in Ayurveda related to Administrative, Academic, Clinical & Research Areas"
author: Dr Kembhavi
email: drkembhavi@live.com

# Navigation menu
header_pages:
  - _pages/about.md
  - _pages/categories.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Site settings
baseurl: ""
url: "https://your-username.github.io"
