title: Dr Kembhavi's Blog
description: "We write everything in Ayurveda related to Administrative, Academic, Clinical, Research & Yoga Areas"
author: Dr Kembhavi
email: drkembhavi@live.com

# Navigation menu - use the working URLs
header_pages:
  - about.md
  - categories.md
  - publications.md

# Build settings
markdown: kramdown
# theme: minima  # Comment out or remove this line to use your custom CSS
plugins:
  - jekyll-feed

# Site settings
baseurl: ""
url: "https://DrKembhavi-s.github.io"

# Custom CSS Configuration
sass:
  style: compressed
  sass_dir: _sass

# Defaults for better organization
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Dr Kembhavi"
  - scope:
      path: "assets/css"
    values:
      sitemap: false
