# _config.yml
title: My Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple blog powered by GitHub Pages and Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
